const result = {
    data:
    {
        "items": [
            {
                "nombre": "fi0_1",
                "valor": "3600802",
                "tipo": "StringField",
                "editable": false,
                "titulo": "Nro de Documento",
                "visible": true,
                "required": true,
                "ayuda": "",
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [],
                "minLength": 1,
                "maxLength": 50
            },
            {
                "valor": null,
                "tipo": "RadioTableField",
                "editable": null,
                "titulo": null,
                "visible": true,
                "required": true,
                "ayuda": null,
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [
                    {
                        "valor": null,
                        "tipo": "HeaderField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "key",
                                "valor": null,
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": null,
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Vencimiento",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Deuda",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Pago Mínimo",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Descripción",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:1:key",
                                "valor": "{\"key\":\"65542.;::;.CUOTA / MEDICINA PREPAGA.;::;.180000.;::;.fdd0b370-ffda-4a99-97e5-6302ec0f6610\",\"customerData\":\"3600802\",\"aditionalData\":\"\",\"vencimiento\":\"Jan 21, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "21/01/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:1:monto",
                                "valor": "180000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "10000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:1:descripcion",
                                "valor": "Nombre Apellido: DERLIS FRANCISCO ZARATE VALDEZ, Id contrato: 65542, Concepto: CUOTA / MEDICINA PREPAGA",
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:2:key",
                                "valor": "{\"key\":\"65542.;::;.DEUDA TOTAL / MEDICINA PREPAGA.;::;.180000.;::;.8b63117e-5653-4e58-b353-d6181e8945d4\",\"customerData\":\"3600802\",\"aditionalData\":\"\",\"vencimiento\":\"Jan 21, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "21/01/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:2:monto",
                                "valor": "180000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "10000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:2:descripcion",
                                "valor": "Nombre Apellido: DERLIS FRANCISCO ZARATE VALDEZ, Id contrato: 65542, Concepto: DEUDA TOTAL / MEDICINA PREPAGA",
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:3:key",
                                "valor": "{\"key\":\"65542.;::;.CUOTAS RESTANTES / MEDICINA PREPAGA.;::;.2340000.;::;.ed52eb06-adfc-41cf-9366-4190c5367bfa\",\"customerData\":\"3600802\",\"aditionalData\":\"\",\"vencimiento\":\"Jan 21, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "21/01/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:3:monto",
                                "valor": "2340000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "10000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:3:descripcion",
                                "valor": "Nombre Apellido: DERLIS FRANCISCO ZARATE VALDEZ, Id contrato: 65542, Concepto: CUOTAS RESTANTES / MEDICINA PREPAGA",
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    }
                ]
            },
            {
                "nombre": "monto",
                "valor": null,
                "tipo": "MoneyField",
                "editable": true,
                "titulo": "Monto a Pagar",
                "visible": true,
                "required": true,
                "ayuda": null,
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": []
            }
        ],
        "info": {
            "duplicateControl": 3633264,
            "documentoPais": null,
            "documentoTipo": null,
            "documentoNumero": "3600802",
            "facturaNro": null,
            "facturaTipo": null,
            "cuotaNro": 0,
            "factDeudaId": null,
            "validBantotalId": null,
            "refDeuda": null,
            "fechaEmision": null,
            "fechaVencimiento": null,
            "fechaProceso": null,
            "deuda": 0,
            "cargo": 0,
            "monto": 0,
            "moneda": 6900,
            "nombre": null,
            "sing": "485d5dd44c9815981594e76f582836ed18086875e41d0cf5391f4c64e0eeec73"
        }
    }
}

module.exports = result;