const result = {
    data: {
    
        "items": [
          {
            "nombre": "fi0_1",
            "valor": "1",
            "tipo": "NumberField",
            "editable": false,
            "titulo": "Tipo de documento",
            "visible": true,
            "required": true,
            "ayuda": "",
            "mostrarEnPasos": null,
            "resumen": false,
            "pattern": "^[1-2]$",
            "multiple": false,
            "html": null,
            "orden": 0,
            "grupoCampos": [],
            "minLength": 1,
            "maxLength": 1
          },
          {
            "nombre": "fi0_2",
            "valor": "4734699",
            "tipo": "StringField",
            "editable": false,
            "titulo": "CI/Nro. de Socio",
            "visible": true,
            "required": true,
            "ayuda": "",
            "mostrarEnPasos": null,
            "resumen": false,
            "pattern": null,
            "multiple": false,
            "html": null,
            "orden": 0,
            "grupoCampos": [],
            "minLength": 1,
            "maxLength": 15
          },
          {
            "valor": null,
            "tipo": "RadioTableField",
            "editable": null,
            "titulo": null,
            "visible": true,
            "required": true,
            "ayuda": null,
            "mostrarEnPasos": null,
            "resumen": false,
            "pattern": null,
            "multiple": false,
            "html": null,
            "orden": 0,
            "grupoCampos": [
              {
                "valor": null,
                "tipo": "HeaderField",
                "editable": null,
                "titulo": null,
                "visible": true,
                "required": false,
                "ayuda": null,
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [
                  {
                    "nombre": "key",
                    "valor": null,
                    "tipo": "HiddenField",
                    "editable": null,
                    "titulo": null,
                    "visible": true,
                    "required": false,
                    "ayuda": null,
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": []
                  },
                  {
                    "valor": null,
                    "tipo": "StringField",
                    "editable": false,
                    "titulo": "Vencimiento",
                    "visible": true,
                    "required": false,
                    "ayuda": null,
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": []
                  },
                  {
                    "valor": null,
                    "tipo": "StringField",
                    "editable": false,
                    "titulo": "Deuda",
                    "visible": true,
                    "required": false,
                    "ayuda": null,
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": []
                  },
                  {
                    "valor": null,
                    "tipo": "StringField",
                    "editable": false,
                    "titulo": "Descripción",
                    "visible": true,
                    "required": false,
                    "ayuda": null,
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": []
                  }
                ]
              },
              {
                "valor": null,
                "tipo": "RowField",
                "editable": null,
                "titulo": null,
                "visible": true,
                "required": false,
                "ayuda": null,
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [
                  {
                    "nombre": "tabla:1:key",
                    "valor": "{\"key\":\"00053635-005-3.;::;.019\",\"customerData\":\"1.;::;.4734699\",\"aditionalData\":\"ALBA AURORA AQUINO MARECO.;::;.19.;::;.456042.;::;.42008.;::;.0.;::;.0.;::;.2871680\",\"vencimiento\":\"Jan 20, 2022 12:00:00 AM\"}",
                    "tipo": "HiddenField",
                    "editable": null,
                    "titulo": "",
                    "visible": true,
                    "required": false,
                    "ayuda": "",
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": []
                  },
                  {
                    "valor": "20/01/2022",
                    "tipo": "DateField",
                    "editable": null,
                    "titulo": "",
                    "visible": true,
                    "required": false,
                    "ayuda": "",
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": []
                  },
                  {
                    "nombre": "tabla:1:monto",
                    "valor": "498050",
                    "tipo": "MoneyField",
                    "editable": null,
                    "titulo": "",
                    "visible": true,
                    "required": false,
                    "ayuda": "",
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": []
                  },
                  {
                    "nombre": "tabla:1:descripcion",
                    "valor": "00053635-005-3",
                    "tipo": "TextareaField",
                    "editable": null,
                    "titulo": "",
                    "visible": true,
                    "required": false,
                    "ayuda": "",
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": []
                  }
                ]
              }
            ]
          }
        ],
        "info": {
          "duplicateControl": 3613811,
          "documentoPais": null,
          "documentoTipo": null,
          "documentoNumero": "4734699",
          "facturaNro": null,
          "facturaTipo": null,
          "cuotaNro": 0,
          "factDeudaId": null,
          "validBantotalId": null,
          "refDeuda": null,
          "fechaEmision": null,
          "fechaVencimiento": null,
          "fechaProceso": null,
          "deuda": 0,
          "cargo": 0,
          "monto": 0,
          "moneda": 6900,
          "nombre": null,
          "sing": "dcf2888a04d6a7b6cef4fea562925112a6cf7c6a937cb109174abf8d60b71939"
        }
      }
  };
  
  module.exports = result;
  