const result = {
    data:
{
	"items": [
		{
			"nombre": "fi0_1",
			"valor": "4194261",
			"tipo": "StringField",
			"editable": false,
			"titulo": "Ced. Identidad",
			"visible": true,
			"required": true,
			"ayuda": "",
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": [],
			"minLength": 1,
			"maxLength": 15
		},
		{
			"valor": null,
			"tipo": "RadioTableField",
			"editable": null,
			"titulo": null,
			"visible": true,
			"required": true,
			"ayuda": null,
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": [
				{
					"valor": null,
					"tipo": "HeaderField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "key",
							"valor": null,
							"tipo": "HiddenField",
							"editable": null,
							"titulo": null,
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Vencimiento",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Deuda",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Descripción",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Usuario",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:1:key",
							"valor": "{\"key\":\"210006433.;::;.606532\",\"customerData\":\"4194261\",\"aditionalData\":\"MARIA SUSANA CORONEL CHAVEZ\",\"vencimiento\":\"Feb 28, 2022 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "28/02/2022",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:1:monto",
							"valor": "263250",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:1:descripcion",
							"valor": "SOL. CORONEL CHAVEZ MARIA SUSANA",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "MARIA SUSANA CORONEL CHAVEZ",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:2:key",
							"valor": "{\"key\":\"210050497.;::;.606532\",\"customerData\":\"4194261\",\"aditionalData\":\"MARIA SUSANA CORONEL CHAVEZ\",\"vencimiento\":\"Mar 31, 2022 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "31/03/2022",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:2:monto",
							"valor": "526500",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:2:descripcion",
							"valor": "SOL. CORONEL CHAVEZ MARIA SUSANA",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "MARIA SUSANA CORONEL CHAVEZ",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				}
			]
		}
	],
	"info": {
		"duplicateControl": 3611420,
		"documentoPais": null,
		"documentoTipo": null,
		"documentoNumero": "4194261",
		"facturaNro": null,
		"facturaTipo": null,
		"cuotaNro": 0,
		"factDeudaId": null,
		"validBantotalId": null,
		"refDeuda": null,
		"fechaEmision": null,
		"fechaVencimiento": null,
		"fechaProceso": null,
		"deuda": 0,
		"cargo": 0,
		"monto": 0,
		"moneda": 6900,
		"nombre": null,
		"sing": "f347961f18d3e968bf16c9e1b8488d9a56ee493c4f790c0d5acfce8c3dd84290"
	}
}
}
module.exports = result;