const result = {
    data:

{
	"items": [
		{
			"nombre": "fi0_1",
			"valor": "3603031",
			"tipo": "StringField",
			"editable": false,
			"titulo": "Documento",
			"visible": true,
			"required": true,
			"ayuda": "",
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": [],
			"minLength": 1,
			"maxLength": 15
		},
		{
			"valor": null,
			"tipo": "RadioTableField",
			"editable": null,
			"titulo": null,
			"visible": true,
			"required": true,
			"ayuda": null,
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": [
				{
					"valor": null,
					"tipo": "HeaderField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "key",
							"valor": null,
							"tipo": "HiddenField",
							"editable": null,
							"titulo": null,
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Vencimiento",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Deuda",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Descripción",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Nombre",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:1:key",
							"valor": "{\"key\":\"4PRE--A0000050060-7\",\"customerData\":\"3603031\",\"aditionalData\":\"Factura Nro:PRE-A-50060 - Cliente: AVEIRO VERA ALEJANDRA BEATRIZ\",\"vencimiento\":\"Feb 1, 2022 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "01/02/2022",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:1:monto",
							"valor": "119000",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:1:descripcion",
							"valor": "Cuota NRO: 7 Producto: ",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "Factura Nro:PRE-A-50060 - Cliente: AVEIRO VERA ALEJANDRA BEATRIZ",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				}
			]
		}
	],
	"info": {
		"duplicateControl": 3606581,
		"documentoPais": null,
		"documentoTipo": null,
		"documentoNumero": "3603031",
		"facturaNro": null,
		"facturaTipo": null,
		"cuotaNro": 0,
		"factDeudaId": null,
		"validBantotalId": null,
		"refDeuda": null,
		"fechaEmision": null,
		"fechaVencimiento": null,
		"fechaProceso": null,
		"deuda": 0,
		"cargo": 0,
		"monto": 0,
		"moneda": 6900,
		"nombre": null,
		"sing": "203ea09d388916b0f5ddf1a42736be788aec0b3d8c7a69ece10fc9267697a358"
	}
}
}


module.exports = result;
