const result = {
    data: {
      items: [
        {
          nombre: 'fi3_1',
          valor: '4331812411278799',
          tipo: 'NumberField',
          editable: false,
          titulo: 'Número de tarjeta',
          visible: true,
          required: true,
          ayuda: '',
          mostrarEnPasos: null,
          resumen: false,
          pattern: '^((401618)|(4016192800)|(401619283)|(4016192860)|(433180)|(433181)|(522217)|(54261218)|(54262124)|(54262128)|(544809)|(54717724)|(54717728)|(60125500)|(60125501)|(60125506)|(861901)|(8624)|(419344))',
          multiple: false,
          html: null,
          orden: 0,
          grupoCampos: [],
          minLength: 1,
          maxLength: 19
        },
        {
          valor: null,
          tipo: 'RadioTableField',
          editable: null,
          titulo: null,
          visible: true,
          required: true,
          ayuda: null,
          mostrarEnPasos: null,
          resumen: false,
          pattern: null,
          multiple: false,
          html: null,
          orden: 0,
          grupoCampos: [
            {
              valor: null,
              tipo: 'HeaderField',
              editable: null,
              titulo: null,
              visible: true,
              required: false,
              ayuda: null,
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: [
                {
                  nombre: 'key',
                  valor: null,
                  tipo: 'HiddenField',
                  editable: null,
                  titulo: null,
                  visible: true,
                  required: false,
                  ayuda: null,
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                },
                {
                  valor: null,
                  tipo: 'StringField',
                  editable: false,
                  titulo: 'Vencimiento',
                  visible: true,
                  required: false,
                  ayuda: null,
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                },
                {
                  valor: null,
                  tipo: 'StringField',
                  editable: false,
                  titulo: 'Deuda',
                  visible: true,
                  required: false,
                  ayuda: null,
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                },
                {
                  valor: null,
                  tipo: 'StringField',
                  editable: false,
                  titulo: 'Pago Mínimo',
                  visible: true,
                  required: false,
                  ayuda: null,
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                },
                {
                  valor: null,
                  tipo: 'StringField',
                  editable: false,
                  titulo: 'Descripción',
                  visible: true,
                  required: false,
                  ayuda: null,
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                },
                {
                  valor: null,
                  tipo: 'StringField',
                  editable: false,
                  titulo: 'Nombre',
                  visible: true,
                  required: false,
                  ayuda: null,
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                }
              ]
            },
            {
              valor: null,
              tipo: 'RowField',
              editable: null,
              titulo: null,
              visible: true,
              required: false,
              ayuda: null,
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: [
                {
                  nombre: 'tabla:1:key',
                  valor: '{"key":"","customerData":"45127272.;::;.433181******8799.;::;..;::;.1","aditionalData":"VASS, JOSE","vencimiento":"Dec 3, 2021 12:00:00 AM"}',
                  tipo: 'HiddenField',
                  editable: null,
                  titulo: '',
                  visible: true,
                  required: false,
                  ayuda: '',
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                },
                {
                  valor: '03/12/2021',
                  tipo: 'DateField',
                  editable: null,
                  titulo: '',
                  visible: true,
                  required: false,
                  ayuda: '',
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                },
                {
                  nombre: 'tabla:1:monto',
                  valor: '2022042',
                  tipo: 'MoneyField',
                  editable: null,
                  titulo: '',
                  visible: true,
                  required: false,
                  ayuda: '',
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                },
                {
                  valor: '208000',
                  tipo: 'MoneyField',
                  editable: null,
                  titulo: '',
                  visible: true,
                  required: false,
                  ayuda: '',
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                },
                {
                  nombre: 'tabla:1:descripcion',
                  valor: null,
                  tipo: 'TextareaField',
                  editable: null,
                  titulo: '',
                  visible: true,
                  required: false,
                  ayuda: '',
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                },
                {
                  valor: 'VASS, JOSE',
                  tipo: 'StringField',
                  editable: null,
                  titulo: '',
                  visible: true,
                  required: false,
                  ayuda: '',
                  mostrarEnPasos: null,
                  resumen: false,
                  pattern: null,
                  multiple: false,
                  html: null,
                  orden: 0,
                  grupoCampos: []
                }
              ]
            }
          ]
        },
        {
          nombre: 'monto',
          valor: null,
          tipo: 'MoneyField',
          editable: true,
          titulo: 'Monto a Pagar',
          visible: true,
          required: true,
          ayuda: null,
          mostrarEnPasos: null,
          resumen: false,
          pattern: null,
          multiple: false,
          html: null,
          orden: 0,
          grupoCampos: []
        }
      ],
      info: {
        duplicateControl: 3488682,
        documentoPais: null,
        documentoTipo: null,
        documentoNumero: '4331********8799',
        facturaNro: null,
        facturaTipo: null,
        cuotaNro: 0,
        factDeudaId: null,
        validBantotalId: null,
        refDeuda: null,
        fechaEmision: null,
        fechaVencimiento: null,
        fechaProceso: null,
        deuda: 0,
        cargo: 0,
        monto: 0,
        moneda: 6900,
        nombre: null,
        sing: 'd960c7d3f14650e598219b11f1ee6cad1adfc845389b73ef6598fd197c7b01f6'
      }
    }
  };

  

  
  module.exports = result;
  