const result = {
    data:
{
	"items": [
		{
			"nombre": "fi0_1",
			"valor": null,
			"tipo": "StringField",
			"editable": true,
			"titulo": "Nro Documento",
			"visible": true,
			"required": true,
			"ayuda": "",
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": [],
			"minLength": 1,
			"maxLength": 20
		},
		{
			"valor": null,
			"tipo": "RadioTableField",
			"editable": null,
			"titulo": null,
			"visible": true,
			"required": true,
			"ayuda": null,
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": [
				{
					"valor": null,
					"tipo": "HeaderField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "key",
							"valor": null,
							"tipo": "HiddenField",
							"editable": null,
							"titulo": null,
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Vencimiento",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Deuda",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Pago Mínimo",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Descripción",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Nombre y Apellido",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:1:key",
							"valor": "{\"key\":\"072161401332.;::;.4.;::;.306335\",\"customerData\":\"4463743\",\"aditionalData\":\"LUCAS ANTONIO RODRIGUEZ RECALDE\",\"vencimiento\":\"Sep 30, 2021 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "30/09/2021",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:1:monto",
							"valor": "306335",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "10000",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:1:descripcion",
							"valor": "Consulta de cuotas",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "LUCAS ANTONIO RODRIGUEZ RECALDE",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:2:key",
							"valor": "{\"key\":\"072161401332.;::;.0.;::;.306335\",\"customerData\":\"4463743\",\"aditionalData\":\"LUCAS ANTONIO RODRIGUEZ RECALDE\",\"vencimiento\":\"Sep 30, 2021 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "30/09/2021",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:2:monto",
							"valor": "306335",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "10000",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:2:descripcion",
							"valor": "Cancelación Cuenta",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "LUCAS ANTONIO RODRIGUEZ RECALDE",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:3:key",
							"valor": "{\"key\":\"072161402685.;::;.1.;::;.1733933\",\"customerData\":\"4463743\",\"aditionalData\":\"LUCAS ANTONIO RODRIGUEZ RECALDE\",\"vencimiento\":\"May 28, 2021 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "28/05/2021",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:3:monto",
							"valor": "1733933",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "10000",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:3:descripcion",
							"valor": "Consulta de cuotas",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "LUCAS ANTONIO RODRIGUEZ RECALDE",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:4:key",
							"valor": "{\"key\":\"072161402685.;::;.0.;::;.1733933\",\"customerData\":\"4463743\",\"aditionalData\":\"LUCAS ANTONIO RODRIGUEZ RECALDE\",\"vencimiento\":\"May 28, 2021 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "28/05/2021",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:4:monto",
							"valor": "1733933",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "10000",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:4:descripcion",
							"valor": "Cancelación Cuenta",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "LUCAS ANTONIO RODRIGUEZ RECALDE",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				}
			]
		},
		{
			"nombre": "monto",
			"valor": null,
			"tipo": "MoneyField",
			"editable": true,
			"titulo": "Monto a Pagar",
			"visible": true,
			"required": true,
			"ayuda": null,
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": []
		}
	],
	"info": {
		"duplicateControl": 3633072,
		"documentoPais": null,
		"documentoTipo": null,
		"documentoNumero": null,
		"facturaNro": null,
		"facturaTipo": null,
		"cuotaNro": 0,
		"factDeudaId": null,
		"validBantotalId": null,
		"refDeuda": null,
		"fechaEmision": null,
		"fechaVencimiento": null,
		"fechaProceso": null,
		"deuda": 0,
		"cargo": 0,
		"monto": 0,
		"moneda": 6900,
		"nombre": null,
		"sing": "1bd34228348da8dddd68fc0f380228c7bf6a395754aac2cb7f52ba3fa2b07d4a"
	}
}
}
module.exports = result;
