const result = {
  data:
{
  items: [
    {
      nombre: 'fi0_1',
      valor: '5467569',
      tipo: 'NumberField',
      editable: false,
      titulo: 'Nro. Documento',
      visible: true,
      required: true,
      ayuda: '',
      mostrarEnPasos: null,
      resumen: false,
      pattern: null,
      multiple: false,
      html: null,
      orden: 0,
      grupoCampos: [],
      minLength: 1,
      maxLength: 20
    },
    {
      valor: null,
      tipo: 'RadioTableField',
      editable: null,
      titulo: null,
      visible: true,
      required: true,
      ayuda: null,
      mostrarEnPasos: null,
      resumen: false,
      pattern: null,
      multiple: false,
      html: null,
      orden: 0,
      grupoCampos: [
        {
          valor: null,
          tipo: 'HeaderField',
          editable: null,
          titulo: null,
          visible: true,
          required: false,
          ayuda: null,
          mostrarEnPasos: null,
          resumen: false,
          pattern: null,
          multiple: false,
          html: null,
          orden: 0,
          grupoCampos: [
            {
              nombre: 'key',
              valor: null,
              tipo: 'HiddenField',
              editable: null,
              titulo: null,
              visible: true,
              required: false,
              ayuda: null,
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              valor: null,
              tipo: 'StringField',
              editable: false,
              titulo: 'Vencimiento',
              visible: true,
              required: false,
              ayuda: null,
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              valor: null,
              tipo: 'StringField',
              editable: false,
              titulo: 'Deuda',
              visible: true,
              required: false,
              ayuda: null,
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              valor: null,
              tipo: 'StringField',
              editable: false,
              titulo: 'Descripción',
              visible: true,
              required: false,
              ayuda: null,
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            }
          ]
        },
        {
          valor: null,
          tipo: 'RowField',
          editable: null,
          titulo: null,
          visible: true,
          required: false,
          ayuda: null,
          mostrarEnPasos: null,
          resumen: false,
          pattern: null,
          multiple: false,
          html: null,
          orden: 0,
          grupoCampos: [
            {
              nombre: 'tabla:1:key',
              valor: '{"key":"9356306","customerData":"5467569","aditionalData":"174.;::;.013.;::;.003.;::;.6","vencimiento":"Jul 10, 2021 12:00:00 AM"}',
              tipo: 'HiddenField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              valor: '10/07/2021',
              tipo: 'DateField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              nombre: 'tabla:1:monto',
              valor: '385472',
              tipo: 'MoneyField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              nombre: 'tabla:1:descripcion',
              valor: 'Fr:174, Manz.:013, Lote:003, cuota: 6 - Cliente: Hernan Castro Sanguina',
              tipo: 'TextareaField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            }
          ]
        },
        {
          valor: null,
          tipo: 'RowField',
          editable: null,
          titulo: null,
          visible: true,
          required: false,
          ayuda: null,
          mostrarEnPasos: null,
          resumen: false,
          pattern: null,
          multiple: false,
          html: null,
          orden: 0,
          grupoCampos: [
            {
              nombre: 'tabla:2:key',
              valor: '{"key":"9356307","customerData":"5467569","aditionalData":"174.;::;.013.;::;.003.;::;.7","vencimiento":"Aug 10, 2021 12:00:00 AM"}',
              tipo: 'HiddenField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              valor: '10/08/2021',
              tipo: 'DateField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              nombre: 'tabla:2:monto',
              valor: '376819',
              tipo: 'MoneyField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              nombre: 'tabla:2:descripcion',
              valor: 'Fr:174, Manz.:013, Lote:003, cuota: 7 - Cliente: Hernan Castro Sanguina',
              tipo: 'TextareaField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            }
          ]
        },
        {
          valor: null,
          tipo: 'RowField',
          editable: null,
          titulo: null,
          visible: true,
          required: false,
          ayuda: null,
          mostrarEnPasos: null,
          resumen: false,
          pattern: null,
          multiple: false,
          html: null,
          orden: 0,
          grupoCampos: [
            {
              nombre: 'tabla:3:key',
              valor: '{"key":"9356308","customerData":"5467569","aditionalData":"174.;::;.013.;::;.003.;::;.8","vencimiento":"Sep 10, 2021 12:00:00 AM"}',
              tipo: 'HiddenField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              valor: '10/09/2021',
              tipo: 'DateField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              nombre: 'tabla:3:monto',
              valor: '368166',
              tipo: 'MoneyField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            },
            {
              nombre: 'tabla:3:descripcion',
              valor: 'Fr:174, Manz.:013, Lote:003, cuota: 8 - Cliente: Hernan Castro Sanguina',
              tipo: 'TextareaField',
              editable: null,
              titulo: '',
              visible: true,
              required: false,
              ayuda: '',
              mostrarEnPasos: null,
              resumen: false,
              pattern: null,
              multiple: false,
              html: null,
              orden: 0,
              grupoCampos: []
            }
          ]
        }
      ]
    }
  ],
  info: {
    duplicateControl: 3598404,
    documentoPais: null,
    documentoTipo: null,
    documentoNumero: '5467569',
    facturaNro: null,
    facturaTipo: null,
    cuotaNro: 0,
    factDeudaId: null,
    validBantotalId: null,
    refDeuda: null,
    fechaEmision: null,
    fechaVencimiento: null,
    fechaProceso: null,
    deuda: 0,
    cargo: 0,
    monto: 0,
    moneda: 6900,
    nombre: null,
    sing: 'b9a95a18ae5ab8cabbb4026a03b7c4f73ca7f102efd1c933904731d2cb88ae4c'
  }
}

};

module.exports = result;
