const result = {
    data:

    {
        "items": [
            {
                "nombre": "fi0_1",
                "valor": "4936093-0",
                "tipo": "StringField",
                "editable": false,
                "titulo": "Ruc",
                "visible": true,
                "required": true,
                "ayuda": "",
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [],
                "minLength": 1,
                "maxLength": 15
            },
            {
                "valor": null,
                "tipo": "RadioTableField",
                "editable": null,
                "titulo": null,
                "visible": true,
                "required": true,
                "ayuda": null,
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [
                    {
                        "valor": null,
                        "tipo": "HeaderField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "key",
                                "valor": null,
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": null,
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Vencimiento",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Deuda",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Descripción",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Cliente",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Periodo",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Factura",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:1:key",
                                "valor": "{\"key\":\"14042346-8903\",\"customerData\":\"4936093-0\",\"aditionalData\":\"ADELINO BACHI.;::;.AGOSTO 2021.;::;.62458\",\"vencimiento\":\"Jan 5, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "05/01/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:1:monto",
                                "valor": "910000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:1:descripcion",
                                "valor": null,
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "ADELINO BACHI",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "AGOSTO 2021",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "62458",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:2:key",
                                "valor": "{\"key\":\"14042346-8905\",\"customerData\":\"4936093-0\",\"aditionalData\":\"ADELINO BACHI.;::;.SEPTIEMBRE 2021.;::;.64024\",\"vencimiento\":\"Jan 5, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "05/01/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:2:monto",
                                "valor": "910000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:2:descripcion",
                                "valor": null,
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "ADELINO BACHI",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "SEPTIEMBRE 2021",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "64024",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:3:key",
                                "valor": "{\"key\":\"14042346-8906\",\"customerData\":\"4936093-0\",\"aditionalData\":\"ADELINO BACHI.;::;.OCTUBRE 2021.;::;.65537\",\"vencimiento\":\"Jan 5, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "05/01/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:3:monto",
                                "valor": "910000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:3:descripcion",
                                "valor": null,
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "ADELINO BACHI",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "OCTUBRE 2021",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "65537",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:4:key",
                                "valor": "{\"key\":\"14042346-8907\",\"customerData\":\"4936093-0\",\"aditionalData\":\"ADELINO BACHI.;::;.NOVIEMBRE 2021.;::;.62458\",\"vencimiento\":\"Jan 5, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "05/01/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:4:monto",
                                "valor": "910000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:4:descripcion",
                                "valor": null,
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "ADELINO BACHI",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "NOVIEMBRE 2021",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "62458",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:5:key",
                                "valor": "{\"key\":\"14042346-8908\",\"customerData\":\"4936093-0\",\"aditionalData\":\"ADELINO BACHI.;::;.DICIEMBRE 2021.;::;.68655\",\"vencimiento\":\"Jan 5, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "05/01/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:5:monto",
                                "valor": "910000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:5:descripcion",
                                "valor": null,
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "ADELINO BACHI",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "DICIEMBRE 2021",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "68655",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:6:key",
                                "valor": "{\"key\":\"14042346-8909\",\"customerData\":\"4936093-0\",\"aditionalData\":\"ADELINO BACHI.;::;.ENERO 2022.;::;.69690\",\"vencimiento\":\"Jan 5, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "05/01/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:6:monto",
                                "valor": "910000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:6:descripcion",
                                "valor": null,
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "ADELINO BACHI",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "ENERO 2022",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "69690",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    }
                ]
            }
        ],
        "info": {
            "duplicateControl": 3642502,
            "documentoPais": null,
            "documentoTipo": null,
            "documentoNumero": "4936093-0",
            "facturaNro": null,
            "facturaTipo": null,
            "cuotaNro": 0,
            "factDeudaId": null,
            "validBantotalId": null,
            "refDeuda": null,
            "fechaEmision": null,
            "fechaVencimiento": null,
            "fechaProceso": null,
            "deuda": 0,
            "cargo": 0,
            "monto": 0,
            "moneda": 6900,
            "nombre": null,
            "sing": "38ddb359fca39b707f4bfd1fdfcfb6372dd866603d9afb76cb43fe70465be994"
        }
    }
}

module.exports = result;
