const result = {
    data:
    {
        "items": [
            {
                "nombre": "fi0_1",
                "valor": "6261613",
                "tipo": "StringField",
                "editable": false,
                "titulo": "Nro Documento",
                "visible": true,
                "required": true,
                "ayuda": "",
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [],
                "minLength": 1,
                "maxLength": 15
            },
            {
                "valor": null,
                "tipo": "RadioTableField",
                "editable": null,
                "titulo": null,
                "visible": true,
                "required": true,
                "ayuda": null,
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [
                    {
                        "valor": null,
                        "tipo": "HeaderField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "key",
                                "valor": null,
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": null,
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Vencimiento",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Deuda",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Descripción",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Nombre y Apellido",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:1:key",
                                "valor": "{\"key\":\"6261613-33-1-2021-4297-9\",\"customerData\":\"6261613\",\"aditionalData\":\"VICTOR DANIEL, SILVA BARRIENTOS\",\"vencimiento\":\"Feb 27, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "27/02/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:1:monto",
                                "valor": "145000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:1:descripcion",
                                "valor": "CUOTA 9/18",
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "VICTOR DANIEL, SILVA BARRIENTOS",
                                "tipo": "StringField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    }
                ]
            }
        ],
        "info": {
            "duplicateControl": 3633917,
            "documentoPais": null,
            "documentoTipo": null,
            "documentoNumero": "6261613",
            "facturaNro": null,
            "facturaTipo": null,
            "cuotaNro": 0,
            "factDeudaId": null,
            "validBantotalId": null,
            "refDeuda": null,
            "fechaEmision": null,
            "fechaVencimiento": null,
            "fechaProceso": null,
            "deuda": 0,
            "cargo": 0,
            "monto": 0,
            "moneda": 6900,
            "nombre": null,
            "sing": "68b4d782d5553f3971e57f7443116eb149be5cf4693740099184b0712d6af573"
        }
    }
}

module.exports = result;