const result = {
  data: {
    items: [
      {
        nombre: 'fi0_1',
        valor: '5103291',
        tipo: 'NumberField',
        editable: false,
        titulo: 'Numero de Documento',
        visible: true,
        required: true,
        ayuda: '',
        mostrarEnPasos: null,
        resumen: false,
        pattern: null,
        multiple: false,
        html: null,
        orden: 0,
        grupoCampos: [],
        minLength: 1,
        maxLength: 30,
      },
      {
        valor: null,
        tipo: 'RadioTableField',
        editable: null,
        titulo: null,
        visible: true,
        required: true,
        ayuda: null,
        mostrarEnPasos: null,
        resumen: false,
        pattern: null,
        multiple: false,
        html: null,
        orden: 0,
        grupoCampos: [
          {
            valor: null,
            tipo: 'HeaderField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'key',
                valor: null,
                tipo: 'HiddenField',
                editable: null,
                titulo: null,
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Vencimiento',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Deuda',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Pago Mínimo',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Descripción',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Nombre Socio',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:1:key',
                valor:
                  '{"key":"5008.;::;.2022-01-10","customerData":"5103291","aditionalData":"BARRIOS VAZQUEZ, ELVIS FERNANDO","vencimiento":"Jan 31, 2022 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '31/01/2022',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:1:monto',
                valor: '334016',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '10000',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:1:descripcion',
                valor: 'Concepto: Préstamos. - Nro. Cuota: 5',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'BARRIOS VAZQUEZ, ELVIS FERNANDO',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
        ],
      },
      {
        nombre: 'monto',
        valor: null,
        tipo: 'MoneyField',
        editable: true,
        titulo: 'Monto a Pagar',
        visible: true,
        required: true,
        ayuda: null,
        mostrarEnPasos: null,
        resumen: false,
        pattern: null,
        multiple: false,
        html: null,
        orden: 0,
        grupoCampos: [],
      },
    ],
    info: {
      duplicateControl: 3607318,
      documentoPais: null,
      documentoTipo: null,
      documentoNumero: '5103291',
      facturaNro: null,
      facturaTipo: null,
      cuotaNro: 0,
      factDeudaId: null,
      validBantotalId: null,
      refDeuda: null,
      fechaEmision: null,
      fechaVencimiento: null,
      fechaProceso: null,
      deuda: 0,
      cargo: 0,
      monto: 0,
      moneda: 6900,
      nombre: null,
      sing: '8c801f86a8c18e3864238c6e1453877b3b5fc1c33d9dd3226f1ee728d43d5ef8',
    },
  },
};

module.exports = result;
