const result = {
    data:
    {
        "items": [
            {
                "nombre": "fi0_1",
                "valor": "5187600",
                "tipo": "StringField",
                "editable": false,
                "titulo": "Cedula Identidad",
                "visible": true,
                "required": true,
                "ayuda": "",
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [],
                "minLength": 4,
                "maxLength": 10
            },
            {
                "valor": null,
                "tipo": "RadioTableField",
                "editable": null,
                "titulo": null,
                "visible": true,
                "required": true,
                "ayuda": null,
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [
                    {
                        "valor": null,
                        "tipo": "HeaderField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "key",
                                "valor": null,
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": null,
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Vencimiento",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Deuda",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Descripción",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:1:key",
                                "valor": "{\"key\":\"11\",\"customerData\":\"5187600\",\"aditionalData\":\"Cuota 12/2021\",\"vencimiento\":\"Dec 1, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "01/12/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:1:monto",
                                "valor": "280500",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:1:descripcion",
                                "valor": "Cuota de diciembre - JESSICA ELIZABETH CABAÑAS SALINAS",
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    }
                ]
            }
        ],
        "info": {
            "duplicateControl": 3634205,
            "documentoPais": null,
            "documentoTipo": null,
            "documentoNumero": "5187600",
            "facturaNro": null,
            "facturaTipo": null,
            "cuotaNro": 0,
            "factDeudaId": null,
            "validBantotalId": null,
            "refDeuda": null,
            "fechaEmision": null,
            "fechaVencimiento": null,
            "fechaProceso": null,
            "deuda": 0,
            "cargo": 0,
            "monto": 0,
            "moneda": 6900,
            "nombre": null,
            "sing": "bbbf67b64eab76a2189d078955312ea77d3651c4a9e47851ac77e6e7afca6311"
        }
    }
}

module.exports = result;