const result = {
  data: {
    items: [
      {
        nombre: 'fi0_1',
        valor: '4755482',
        tipo: 'StringField',
        editable: false,
        titulo: 'Ced. Identidad',
        visible: true,
        required: true,
        ayuda: '',
        mostrarEnPasos: null,
        resumen: false,
        pattern: null,
        multiple: false,
        html: null,
        orden: 0,
        grupoCampos: [],
        minLength: 1,
        maxLength: 15,
      },
      {
        valor: null,
        tipo: 'RadioTableField',
        editable: null,
        titulo: null,
        visible: true,
        required: true,
        ayuda: null,
        mostrarEnPasos: null,
        resumen: false,
        pattern: null,
        multiple: false,
        html: null,
        orden: 0,
        grupoCampos: [
          {
            valor: null,
            tipo: 'HeaderField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'key',
                valor: null,
                tipo: 'HiddenField',
                editable: null,
                titulo: null,
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Vencimiento',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Deuda',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Descripción',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Usuario',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:1:key',
                valor:
                  '{"key":"28973470.;::;.609184","customerData":"4755482","aditionalData":"BRUNILDE KARINA SAMANIEGO VILLALBA","vencimiento":"Jan 31, 2023 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '31/01/2023',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:1:monto',
                valor: '440000',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:1:descripcion',
                valor: 'MANTENIMIENTO ANUAL LOTE FUTURO - PROP: 18059 - A-',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'BRUNILDE KARINA SAMANIEGO VILLALBA',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:2:key',
                valor:
                  '{"key":"28973471.;::;.609184","customerData":"4755482","aditionalData":"BRUNILDE KARINA SAMANIEGO VILLALBA","vencimiento":"Jan 31, 2024 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '31/01/2024',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:2:monto',
                valor: '880000',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:2:descripcion',
                valor: 'MANTENIMIENTO ANUAL LOTE FUTURO - PROP: 18059 - A-',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'BRUNILDE KARINA SAMANIEGO VILLALBA',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:3:key',
                valor:
                  '{"key":"28973472.;::;.609184","customerData":"4755482","aditionalData":"BRUNILDE KARINA SAMANIEGO VILLALBA","vencimiento":"Jan 31, 2025 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '31/01/2025',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:3:monto',
                valor: '1320000',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:3:descripcion',
                valor: 'MANTENIMIENTO ANUAL LOTE FUTURO - PROP: 18059 - A-',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'BRUNILDE KARINA SAMANIEGO VILLALBA',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:4:key',
                valor:
                  '{"key":"28973473.;::;.609184","customerData":"4755482","aditionalData":"BRUNILDE KARINA SAMANIEGO VILLALBA","vencimiento":"Jan 31, 2026 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '31/01/2026',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:4:monto',
                valor: '1760000',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:4:descripcion',
                valor: 'MANTENIMIENTO ANUAL LOTE FUTURO - PROP: 18059 - A-',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'BRUNILDE KARINA SAMANIEGO VILLALBA',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:5:key',
                valor:
                  '{"key":"28973474.;::;.609184","customerData":"4755482","aditionalData":"BRUNILDE KARINA SAMANIEGO VILLALBA","vencimiento":"Jan 31, 2027 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '31/01/2027',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:5:monto',
                valor: '2200000',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:5:descripcion',
                valor: 'MANTENIMIENTO ANUAL LOTE FUTURO - PROP: 18059 - A-',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'BRUNILDE KARINA SAMANIEGO VILLALBA',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
        ],
      },
    ],
    info: {
      duplicateControl: 3610839,
      documentoPais: null,
      documentoTipo: null,
      documentoNumero: '4755482',
      facturaNro: null,
      facturaTipo: null,
      cuotaNro: 0,
      factDeudaId: null,
      validBantotalId: null,
      refDeuda: null,
      fechaEmision: null,
      fechaVencimiento: null,
      fechaProceso: null,
      deuda: 0,
      cargo: 0,
      monto: 0,
      moneda: 6900,
      nombre: null,
      sing: 'd565125c2d361b39a4bcfac4fc2e665e40c8c4358b92752da81cfed23f57ecda',
    },
  },
};

module.exports = result;
