const result = {
    data:
    {
        "items": [
            {
                "nombre": "fi0_1",
                "valor": "5639034",
                "tipo": "StringField",
                "editable": false,
                "titulo": "Cédula de Identidad o RUC",
                "visible": true,
                "required": true,
                "ayuda": "",
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [],
                "minLength": 4,
                "maxLength": 11
            },
            {
                "valor": null,
                "tipo": "RadioTableField",
                "editable": null,
                "titulo": null,
                "visible": true,
                "required": true,
                "ayuda": null,
                "mostrarEnPasos": null,
                "resumen": false,
                "pattern": null,
                "multiple": false,
                "html": null,
                "orden": 0,
                "grupoCampos": [
                    {
                        "valor": null,
                        "tipo": "HeaderField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "key",
                                "valor": null,
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": null,
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Vencimiento",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Deuda",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": null,
                                "tipo": "StringField",
                                "editable": false,
                                "titulo": "Descripción",
                                "visible": true,
                                "required": false,
                                "ayuda": null,
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:1:key",
                                "valor": "{\"key\":\"1379521.;::;.6.;::;.1\",\"customerData\":\"5639034\",\"aditionalData\":\"FPJ - SARA FRANCO - VENTAS TERCERIZADAS REM - PRESTAMOS PERSONALES FIADO\",\"vencimiento\":\"Feb 3, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "03/02/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:1:monto",
                                "valor": "188000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:1:descripcion",
                                "valor": "SARA FRANCO, Prestamo:1379521, Cuota: 6",
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:2:key",
                                "valor": "{\"key\":\"1379521.;::;.7.;::;.1\",\"customerData\":\"5639034\",\"aditionalData\":\"FPJ - SARA FRANCO - VENTAS TERCERIZADAS REM - PRESTAMOS PERSONALES FIADO\",\"vencimiento\":\"Mar 3, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "03/03/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:2:monto",
                                "valor": "188000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:2:descripcion",
                                "valor": "SARA FRANCO, Prestamo:1379521, Cuota: 7",
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    },
                    {
                        "valor": null,
                        "tipo": "RowField",
                        "editable": null,
                        "titulo": null,
                        "visible": true,
                        "required": false,
                        "ayuda": null,
                        "mostrarEnPasos": null,
                        "resumen": false,
                        "pattern": null,
                        "multiple": false,
                        "html": null,
                        "orden": 0,
                        "grupoCampos": [
                            {
                                "nombre": "tabla:3:key",
                                "valor": "{\"key\":\"1379521.;::;.8.;::;.1\",\"customerData\":\"5639034\",\"aditionalData\":\"FPJ - SARA FRANCO - VENTAS TERCERIZADAS REM - PRESTAMOS PERSONALES FIADO\",\"vencimiento\":\"Apr 4, 2022 12:00:00 AM\"}",
                                "tipo": "HiddenField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "valor": "04/04/2022",
                                "tipo": "DateField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:3:monto",
                                "valor": "188000",
                                "tipo": "MoneyField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            },
                            {
                                "nombre": "tabla:3:descripcion",
                                "valor": "SARA FRANCO, Prestamo:1379521, Cuota: 8",
                                "tipo": "TextareaField",
                                "editable": null,
                                "titulo": "",
                                "visible": true,
                                "required": false,
                                "ayuda": "",
                                "mostrarEnPasos": null,
                                "resumen": false,
                                "pattern": null,
                                "multiple": false,
                                "html": null,
                                "orden": 0,
                                "grupoCampos": []
                            }
                        ]
                    }
                ]
            }
        ],
        "info": {
            "duplicateControl": 3633004,
            "documentoPais": null,
            "documentoTipo": null,
            "documentoNumero": "5639034",
            "facturaNro": null,
            "facturaTipo": null,
            "cuotaNro": 0,
            "factDeudaId": null,
            "validBantotalId": null,
            "refDeuda": null,
            "fechaEmision": null,
            "fechaVencimiento": null,
            "fechaProceso": null,
            "deuda": 0,
            "cargo": 0,
            "monto": 0,
            "moneda": 6900,
            "nombre": null,
            "sing": "ff0934f368aed25ef7cdab02d5eab9cb30f61ec089f551f70f58f2c70aa8bf1b"
        }
    }
}
module.exports = result;
