const result = {
    data:
{
	"items": [
		{
			"nombre": "fi0_1",
			"valor": "4755482",
			"tipo": "NumberField",
			"editable": false,
			"titulo": "Número de Documento",
			"visible": true,
			"required": true,
			"ayuda": "",
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": [],
			"minLength": 1,
			"maxLength": 20
		},
		{
			"valor": null,
			"tipo": "RadioTableField",
			"editable": null,
			"titulo": null,
			"visible": true,
			"required": true,
			"ayuda": null,
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": [
				{
					"valor": null,
					"tipo": "HeaderField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "key",
							"valor": null,
							"tipo": "HiddenField",
							"editable": null,
							"titulo": null,
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Vencimiento",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Deuda",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Descripción",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Nombre Apellido",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:1:key",
							"valor": "{\"key\":\"83996.;::;.398910.;::;.1.;::;.05/02/2022\",\"customerData\":\"4755482\",\"aditionalData\":\"BRUNILDE KARINA SAMANIEGO VILLALBA\",\"vencimiento\":\"Feb 5, 2022 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "05/02/2022",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:1:monto",
							"valor": "414958",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:1:descripcion",
							"valor": "ESCOLAR-CATEGORIA A",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "BRUNILDE KARINA SAMANIEGO VILLALBA",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				}
			]
		}
	],
	"info": {
		"duplicateControl": 3603954,
		"documentoPais": null,
		"documentoTipo": null,
		"documentoNumero": "4755482",
		"facturaNro": null,
		"facturaTipo": null,
		"cuotaNro": 0,
		"factDeudaId": null,
		"validBantotalId": null,
		"refDeuda": null,
		"fechaEmision": null,
		"fechaVencimiento": null,
		"fechaProceso": null,
		"deuda": 0,
		"cargo": 0,
		"monto": 0,
		"moneda": 6900,
		"nombre": null,
		"sing": "2f0c20395d315cf5e2957ee16505f6c7d7f5ede053be178506e290d8d909279d"
	}
}
}

module.exports = result;
      