const result = {
    data:
{
	"items": [
		{
			"nombre": "fi0_1",
			"valor": "4755482",
			"tipo": "StringField",
			"editable": false,
			"titulo": "Ced. Identidad",
			"visible": true,
			"required": true,
			"ayuda": "",
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": [],
			"minLength": 1,
			"maxLength": 15
		},
		{
			"valor": null,
			"tipo": "RadioTableField",
			"editable": null,
			"titulo": null,
			"visible": true,
			"required": true,
			"ayuda": null,
			"mostrarEnPasos": null,
			"resumen": false,
			"pattern": null,
			"multiple": false,
			"html": null,
			"orden": 0,
			"grupoCampos": [
				{
					"valor": null,
					"tipo": "HeaderField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "key",
							"valor": null,
							"tipo": "HiddenField",
							"editable": null,
							"titulo": null,
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Vencimiento",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Deuda",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Descripción",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": null,
							"tipo": "StringField",
							"editable": false,
							"titulo": "Usuario",
							"visible": true,
							"required": false,
							"ayuda": null,
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:1:key",
							"valor": "{\"key\":\"18251044.;::;.19505\",\"customerData\":\"4755482\",\"aditionalData\":\"BRUNILDE KARINA SAMANIEGO VILLALBA\",\"vencimiento\":\"Jan 12, 2022 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "12/01/2022",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:1:monto",
							"valor": "295600",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:1:descripcion",
							"valor": "PLAN PARCELAS PF",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "BRUNILDE KARINA SAMANIEGO VILLALBA",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:2:key",
							"valor": "{\"key\":\"18251045.;::;.19505\",\"customerData\":\"4755482\",\"aditionalData\":\"BRUNILDE KARINA SAMANIEGO VILLALBA\",\"vencimiento\":\"Feb 12, 2022 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "12/02/2022",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:2:monto",
							"valor": "591200",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:2:descripcion",
							"valor": "PLAN PARCELAS PF",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "BRUNILDE KARINA SAMANIEGO VILLALBA",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:3:key",
							"valor": "{\"key\":\"18251046.;::;.19505\",\"customerData\":\"4755482\",\"aditionalData\":\"BRUNILDE KARINA SAMANIEGO VILLALBA\",\"vencimiento\":\"Mar 12, 2022 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "12/03/2022",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:3:monto",
							"valor": "886800",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:3:descripcion",
							"valor": "PLAN PARCELAS PF",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "BRUNILDE KARINA SAMANIEGO VILLALBA",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:4:key",
							"valor": "{\"key\":\"18251047.;::;.19505\",\"customerData\":\"4755482\",\"aditionalData\":\"BRUNILDE KARINA SAMANIEGO VILLALBA\",\"vencimiento\":\"Apr 12, 2022 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "12/04/2022",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:4:monto",
							"valor": "1182400",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:4:descripcion",
							"valor": "PLAN PARCELAS PF",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "BRUNILDE KARINA SAMANIEGO VILLALBA",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				},
				{
					"valor": null,
					"tipo": "RowField",
					"editable": null,
					"titulo": null,
					"visible": true,
					"required": false,
					"ayuda": null,
					"mostrarEnPasos": null,
					"resumen": false,
					"pattern": null,
					"multiple": false,
					"html": null,
					"orden": 0,
					"grupoCampos": [
						{
							"nombre": "tabla:5:key",
							"valor": "{\"key\":\"18251048.;::;.19505\",\"customerData\":\"4755482\",\"aditionalData\":\"BRUNILDE KARINA SAMANIEGO VILLALBA\",\"vencimiento\":\"May 12, 2022 12:00:00 AM\"}",
							"tipo": "HiddenField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "12/05/2022",
							"tipo": "DateField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:5:monto",
							"valor": "1478000",
							"tipo": "MoneyField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"nombre": "tabla:5:descripcion",
							"valor": "PLAN PARCELAS PF",
							"tipo": "TextareaField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						},
						{
							"valor": "BRUNILDE KARINA SAMANIEGO VILLALBA",
							"tipo": "StringField",
							"editable": null,
							"titulo": "",
							"visible": true,
							"required": false,
							"ayuda": "",
							"mostrarEnPasos": null,
							"resumen": false,
							"pattern": null,
							"multiple": false,
							"html": null,
							"orden": 0,
							"grupoCampos": []
						}
					]
				}
			]
		}
	],
	"info": {
		"duplicateControl": 3611826,
		"documentoPais": null,
		"documentoTipo": null,
		"documentoNumero": "4755482",
		"facturaNro": null,
		"facturaTipo": null,
		"cuotaNro": 0,
		"factDeudaId": null,
		"validBantotalId": null,
		"refDeuda": null,
		"fechaEmision": null,
		"fechaVencimiento": null,
		"fechaProceso": null,
		"deuda": 0,
		"cargo": 0,
		"monto": 0,
		"moneda": 6900,
		"nombre": null,
		"sing": "a9be0915d8192e76f32c911c8bda1b9ff14549945dba17db0c69c6706e37e67d"
	}
}
}
module.exports = result;