const result = {
  data: {
    items: [
      {
        nombre: 'fi0_1',
        valor: '3237837',
        tipo: 'StringField',
        editable: false,
        titulo: 'Documento',
        visible: true,
        required: true,
        ayuda: '',
        mostrarEnPasos: null,
        resumen: false,
        pattern: null,
        multiple: false,
        html: null,
        orden: 0,
        grupoCampos: [],
        minLength: 1,
        maxLength: 15,
      },
      {
        valor: null,
        tipo: 'RadioTableField',
        editable: null,
        titulo: null,
        visible: true,
        required: true,
        ayuda: null,
        mostrarEnPasos: null,
        resumen: false,
        pattern: null,
        multiple: false,
        html: null,
        orden: 0,
        grupoCampos: [
          {
            valor: null,
            tipo: 'HeaderField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'key',
                valor: null,
                tipo: 'HiddenField',
                editable: null,
                titulo: null,
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Vencimiento',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Deuda',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Descripción',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: null,
                tipo: 'StringField',
                editable: false,
                titulo: 'Nombre',
                visible: true,
                required: false,
                ayuda: null,
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:1:key',
                valor:
                  '{"key":"5002010086527.;::;.8105454","customerData":"3237837","aditionalData":"CACERES RIOS, AIDA SUNILDA ","vencimiento":"Jan 9, 2022 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '09/01/2022',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:1:monto',
                valor: '90097',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:1:descripcion',
                valor: 'Poliza: 5002010086527 Cuota: 1-VILLARRIZA C A 10/01',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'CACERES RIOS, AIDA SUNILDA ',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:2:key',
                valor:
                  '{"key":"5002010086527.;::;.8105455","customerData":"3237837","aditionalData":"CACERES RIOS, AIDA SUNILDA ","vencimiento":"Feb 9, 2022 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '09/02/2022',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:2:monto',
                valor: '180194',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:2:descripcion',
                valor: 'Poliza: 5002010086527 Cuota: 2-VILLARRIZA C A FEB',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'CACERES RIOS, AIDA SUNILDA ',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:3:key',
                valor:
                  '{"key":"5002010086527.;::;.8105456","customerData":"3237837","aditionalData":"CACERES RIOS, AIDA SUNILDA ","vencimiento":"Mar 9, 2022 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '09/03/2022',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:3:monto',
                valor: '270291',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:3:descripcion',
                valor: 'Poliza: 5002010086527 Cuota: 3-VILLARRIZA C A MAR',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'CACERES RIOS, AIDA SUNILDA ',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:4:key',
                valor:
                  '{"key":"5002010086527.;::;.8105457","customerData":"3237837","aditionalData":"CACERES RIOS, AIDA SUNILDA ","vencimiento":"Apr 9, 2022 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '09/04/2022',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:4:monto',
                valor: '360388',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:4:descripcion',
                valor: 'Poliza: 5002010086527 Cuota: 4-VILLARRIZA C A ABR',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'CACERES RIOS, AIDA SUNILDA ',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
          {
            valor: null,
            tipo: 'RowField',
            editable: null,
            titulo: null,
            visible: true,
            required: false,
            ayuda: null,
            mostrarEnPasos: null,
            resumen: false,
            pattern: null,
            multiple: false,
            html: null,
            orden: 0,
            grupoCampos: [
              {
                nombre: 'tabla:5:key',
                valor:
                  '{"key":"5002010086527.;::;.8105458","customerData":"3237837","aditionalData":"CACERES RIOS, AIDA SUNILDA ","vencimiento":"May 9, 2022 12:00:00 AM"}',
                tipo: 'HiddenField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: '09/05/2022',
                tipo: 'DateField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:5:monto',
                valor: '450484',
                tipo: 'MoneyField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                nombre: 'tabla:5:descripcion',
                valor: 'Poliza: 5002010086527 Cuota: 5-VILLARRIZA C A MAY',
                tipo: 'TextareaField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
              {
                valor: 'CACERES RIOS, AIDA SUNILDA ',
                tipo: 'StringField',
                editable: null,
                titulo: '',
                visible: true,
                required: false,
                ayuda: '',
                mostrarEnPasos: null,
                resumen: false,
                pattern: null,
                multiple: false,
                html: null,
                orden: 0,
                grupoCampos: [],
              },
            ],
          },
        ],
      },
    ],
    info: {
      duplicateControl: 3606746,
      documentoPais: null,
      documentoTipo: null,
      documentoNumero: '3237837',
      facturaNro: null,
      facturaTipo: null,
      cuotaNro: 0,
      factDeudaId: null,
      validBantotalId: null,
      refDeuda: null,
      fechaEmision: null,
      fechaVencimiento: null,
      fechaProceso: null,
      deuda: 0,
      cargo: 0,
      monto: 0,
      moneda: 6900,
      nombre: null,
      sing: 'a646676bec8377160b0001738f5aaf09b0b147f7676587901c59d2b76a3b355e',
    },
  },
};

module.exports = result;
