const result = {
    data: {
            "items": [
                {
                    "nombre": "fi0_1",
                    "valor": "4807762",
                    "tipo": "StringField",
                    "editable": false,
                    "titulo": "Número de Documento",
                    "visible": true,
                    "required": true,
                    "ayuda": "",
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": [],
                    "minLength": 1,
                    "maxLength": 15
                },
                {
                    "valor": null,
                    "tipo": "RadioTableField",
                    "editable": null,
                    "titulo": null,
                    "visible": true,
                    "required": true,
                    "ayuda": null,
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": [
                        {
                            "valor": null,
                            "tipo": "HeaderField",
                            "editable": null,
                            "titulo": null,
                            "visible": true,
                            "required": false,
                            "ayuda": null,
                            "mostrarEnPasos": null,
                            "resumen": false,
                            "pattern": null,
                            "multiple": false,
                            "html": null,
                            "orden": 0,
                            "grupoCampos": [
                                {
                                    "nombre": "key",
                                    "valor": null,
                                    "tipo": "HiddenField",
                                    "editable": null,
                                    "titulo": null,
                                    "visible": true,
                                    "required": false,
                                    "ayuda": null,
                                    "mostrarEnPasos": null,
                                    "resumen": false,
                                    "pattern": null,
                                    "multiple": false,
                                    "html": null,
                                    "orden": 0,
                                    "grupoCampos": []
                                },
                                {
                                    "valor": null,
                                    "tipo": "StringField",
                                    "editable": false,
                                    "titulo": "Vencimiento",
                                    "visible": true,
                                    "required": false,
                                    "ayuda": null,
                                    "mostrarEnPasos": null,
                                    "resumen": false,
                                    "pattern": null,
                                    "multiple": false,
                                    "html": null,
                                    "orden": 0,
                                    "grupoCampos": []
                                },
                                {
                                    "valor": null,
                                    "tipo": "StringField",
                                    "editable": false,
                                    "titulo": "Deuda",
                                    "visible": true,
                                    "required": false,
                                    "ayuda": null,
                                    "mostrarEnPasos": null,
                                    "resumen": false,
                                    "pattern": null,
                                    "multiple": false,
                                    "html": null,
                                    "orden": 0,
                                    "grupoCampos": []
                                },
                                {
                                    "valor": null,
                                    "tipo": "StringField",
                                    "editable": false,
                                    "titulo": "Pago Mínimo",
                                    "visible": true,
                                    "required": false,
                                    "ayuda": null,
                                    "mostrarEnPasos": null,
                                    "resumen": false,
                                    "pattern": null,
                                    "multiple": false,
                                    "html": null,
                                    "orden": 0,
                                    "grupoCampos": []
                                },
                                {
                                    "valor": null,
                                    "tipo": "StringField",
                                    "editable": false,
                                    "titulo": "Descripción",
                                    "visible": true,
                                    "required": false,
                                    "ayuda": null,
                                    "mostrarEnPasos": null,
                                    "resumen": false,
                                    "pattern": null,
                                    "multiple": false,
                                    "html": null,
                                    "orden": 0,
                                    "grupoCampos": []
                                }
                            ]
                        },
                        {
                            "valor": null,
                            "tipo": "RowField",
                            "editable": null,
                            "titulo": null,
                            "visible": true,
                            "required": false,
                            "ayuda": null,
                            "mostrarEnPasos": null,
                            "resumen": false,
                            "pattern": null,
                            "multiple": false,
                            "html": null,
                            "orden": 0,
                            "grupoCampos": [
                                {
                                    "nombre": "tabla:1:key",
                                    "valor": "{\"key\":\"1110017703-1\",\"customerData\":\"4807762\",\"aditionalData\":\"Nro Prestamo: 1110017703 - Cliente: ALBA GRACIELA BENITEZ FIGUEREDO\",\"vencimiento\":\"Jan 5, 2022 12:00:00 AM\"}",
                                    "tipo": "HiddenField",
                                    "editable": null,
                                    "titulo": "",
                                    "visible": true,
                                    "required": false,
                                    "ayuda": "",
                                    "mostrarEnPasos": null,
                                    "resumen": false,
                                    "pattern": null,
                                    "multiple": false,
                                    "html": null,
                                    "orden": 0,
                                    "grupoCampos": []
                                },
                                {
                                    "valor": "05/01/2022",
                                    "tipo": "DateField",
                                    "editable": null,
                                    "titulo": "",
                                    "visible": true,
                                    "required": false,
                                    "ayuda": "",
                                    "mostrarEnPasos": null,
                                    "resumen": false,
                                    "pattern": null,
                                    "multiple": false,
                                    "html": null,
                                    "orden": 0,
                                    "grupoCampos": []
                                },
                                {
                                    "nombre": "tabla:1:monto",
                                    "valor": "316656",
                                    "tipo": "MoneyField",
                                    "editable": null,
                                    "titulo": "",
                                    "visible": true,
                                    "required": false,
                                    "ayuda": "",
                                    "mostrarEnPasos": null,
                                    "resumen": false,
                                    "pattern": null,
                                    "multiple": false,
                                    "html": null,
                                    "orden": 0,
                                    "grupoCampos": []
                                },
                                {
                                    "valor": "316656",
                                    "tipo": "MoneyField",
                                    "editable": null,
                                    "titulo": "",
                                    "visible": true,
                                    "required": false,
                                    "ayuda": "",
                                    "mostrarEnPasos": null,
                                    "resumen": false,
                                    "pattern": null,
                                    "multiple": false,
                                    "html": null,
                                    "orden": 0,
                                    "grupoCampos": []
                                },
                                {
                                    "nombre": "tabla:1:descripcion",
                                    "valor": "Cuota Nro. 1",
                                    "tipo": "TextareaField",
                                    "editable": null,
                                    "titulo": "",
                                    "visible": true,
                                    "required": false,
                                    "ayuda": "",
                                    "mostrarEnPasos": null,
                                    "resumen": false,
                                    "pattern": null,
                                    "multiple": false,
                                    "html": null,
                                    "orden": 0,
                                    "grupoCampos": []
                                }
                            ]
                        }
                    ]
                },
                {
                    "nombre": "monto",
                    "valor": null,
                    "tipo": "MoneyField",
                    "editable": true,
                    "titulo": "Monto a Pagar",
                    "visible": true,
                    "required": true,
                    "ayuda": null,
                    "mostrarEnPasos": null,
                    "resumen": false,
                    "pattern": null,
                    "multiple": false,
                    "html": null,
                    "orden": 0,
                    "grupoCampos": []
                }
            ],
            "info": {
                "duplicateControl": 3548947,
                "documentoPais": null,
                "documentoTipo": null,
                "documentoNumero": "4807762",
                "facturaNro": null,
                "facturaTipo": null,
                "cuotaNro": 0,
                "factDeudaId": null,
                "validBantotalId": null,
                "refDeuda": null,
                "fechaEmision": null,
                "fechaVencimiento": null,
                "fechaProceso": null,
                "deuda": 0,
                "cargo": 0,
                "monto": 0,
                "moneda": 6900,
                "nombre": null,
                "sing": "8d35c1c4f313300628399e52a5a9a87733e39663b399d86e92750e7e350145f6"
            }
        }  
  }

  
  module.exports = result;
  