name: produ-deploy
on:
  release:
    types: [published]
env:
  REGISTRY: 'registry.digitalocean.com/redisa'
  IMAGE_NAME: 'redisa_facturadores'
  VERSION: 'produ'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $VERSION) .

      - name: Tag to registry
        run: docker tag $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $VERSION) $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $VERSION)

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $VERSION)

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/wepaproduserver.key
          chmod 600 ~/.ssh/wepaproduserver.key
          cat >>~/.ssh/config <<END
          Host wepaproduserver
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/wepaproduserver.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY_PRODU }}
          SSH_HOST: ${{ secrets.SSH_HOST_PRODU }}

      - name: Update beFacturadores
        run: ssh wepaproduserver 'sh /home/wepa/scripts/beFacturadoresProdu-update.sh'
